### ISSUE TITLE
Small website bugs. 

### ISSUE THREAD

**Issue by vigsiv** [sreachtools/SReachTools#1]
Hi, 

I noticed a few bugs on the website. Namely the GitHub logo is off center from the "SReachTools" logo as well as citation 7 missing (it comes up as [^7]). 

![image](https://user-images.githubusercontent.com/35810961/48789634-baf4c900-ecaa-11e8-92be-90e70f4bc965.png)

![image](https://user-images.githubusercontent.com/35810961/48789663-cd6f0280-ecaa-11e8-94ae-225569c9f5f4.png)

Thanks!

System: Ubuntu 18.04
Browser: Chrome (Version 70.0.3538.77 (Official Build) (64-bit))

**Comment by gleasonj** [comment]
The aforementioned issues have been fixed. Thanks for bringing it to our attention. 

Will leave this open in case you notice anything else. :)
