### ISSUE TITLE
disp of LtiSystem with verbose=True produces error

### ISSUE THREAD

**Issue by stanleybak** [sreachtools/SReachTools#2]
I tried to `disp(sys, 'verbose', True)` on an LTI system from `getCwhLtiSystem` and an error was raised since it called `func2str(obj.state_mat)`, where the `state_mat` is a double, not a function.

Here's an error trace:
```
Undefined function 'func2str' for input arguments of type 'double'.

Error in LtiSystem/disp (line 195)
                    func2str(obj.state_mat), ...

Error in cwhSReachSetCodeOcean (line 79)
disp(sys, 'verbose', true)
```

The error is shown on the line `LtiSystem/disp (line 195)`

**Comment by abyvinod** [comment]
@stanleybak Thanks for catching this bug. I will work on it.
